# --- General options --- #
# port: 4000
# host: 127.0.0.1
# To run in jekyll: bundle exec jekyll serve
# and go to http://127.0.0.1:4000/

# If you are building a GitHub project page:
#url: "http://username.github.io/projectname"
#baseurl: "/projectname"

# Name of website
title: Rivers & Ranids
bigimg: "/img/20150912_shallnotpass.jpg"

# Short description of your site
url: "http://ryanpeek.github.io"
baseurl: ""
description: A blog about Rivers (and Frogs)!


# --- Navigation bar options --- #

# List of links in the navigation bar
navbar-links:
  About Me:
    - Quick Bio: "aboutme"
    - CV: "cv"
    - Archives: "tags"
  Research:
    - Rana boylii: "RABO_sites_flexdash.html"
    - RADSeq/RAPTURE Pipeline: "https://ryanpeek.github.io/radseq"
    - Sierra Rivers Monitoring: "https://watershed.ucdavis.edu/project/long-term-river-monitoring"
    - River Time-Lapse: "https://vimeo.com/164154774"
    - Meadows: "http://meadows.ucdavis.edu"
  Shiny Apps:
    - Thermohydrographs: "http://shiny.cws.ucdavis.edu/shiny/rapeek/thermohydrographs/"
    - Humboldt NWR Climate: "http://shiny.cws.ucdavis.edu/shiny/rapeek/Humboldt_GCM/"
    - Tadpole Gosner Staging: "http://shiny.cws.ucdavis.edu/shiny/rapeek/Gosner_photos/"
  Resources:
    - AggieBrickyard: "https://aggiebrickyard.github.io/"
    - Data Carpentry: "http://www.datacarpentry.org/"
    - Davis R Users Group: "https://d-rug.github.io/"
    - Beautiful Jekyll: "http://deanattali.com/beautiful-jekyll/"

# Image to show in the navigation bar - image must be a square (width = height)
# Remove this parameter if you don't want an image in the navbar
avatar: "/img/P1080821.JPG"

# --- Footer options --- #

# Change all these values or delete the ones you don't want.
# Important: you must keep the "name" parameter, everything else you can remove
author:
  name: Ryan
  email: "rapeek @ ucdavis.edu"
  facebook: yourname  # eg. daattali
  github: ryanpeek
  twitter: riverpeek
  linkedin: yourlink  # eg. "pub/dean-attali/8/946/143"
  stackoverflow: yourlink  # eg. "3943160/daattali"



# Select which links to show in the footer
footer-links-active:
  rss: true
  facebook: false
  email: true
  twitter: true
  github: true
  linkedin: false
  stackoverflow: false

# How to display the link to the website in the footer
# Remove this if you don't want a link in the footer
url-pretty: "ryanpeek.github.io"

# --- Misc --- #

# Fill in your Disqus shortname (NOT the userid) if you want to support Disqus comments
disqus: "ryanpeek-github-io"

# Fill in your Google Analytics ID to track your website using GA
google_analytics: "UA-87260839-1"
# old through gmail "UA-80552998-1"

# --- Don't need to touch anything below here (but you can if you want) --- #

# Output options (more information on Jekyll's site)
timezone: "America/Vancouver"
markdown: kramdown
highlighter: rouge
permalink: /:year-:month-:day-:title/
paginate: 5

kramdown:
  input: GFM

# Default YAML values (more information on Jekyll's site)
defaults:
  -
    scope:
      path: ""
      type: "posts"
    values:
      layout: "post"
      comments: true  # add comments to all blog posts
  -
    scope:
      path: "" # all files
    values:
      layout: "page"
      show-avatar: true

# Exclude these files from production site
exclude:
  - Gemfile
  - Gemfile.lock
  - LICENSE
  - README.md
  - CNAME
  - Vagrantfile
  - .DS_Store

# prose.io config
prose:
  rooturl: '_posts'
  media: 'img'
  ignore:
    - 404.html
    - LICENSE
    - feed.xml
    - _config.yml
    - /_layouts
    - /_includes
    - /css
    - /img
    - /js
  metadata:
    _posts:
      - name: "layout"
        field:
          element: "hidden"
          value: "post"
      - name: "title"
        field:
          element: "text"
          label: "Post title"
          placeholder: "Title"
          alterable: true
      - name: "subtitle"
        field:
          element: "textarea"
          label: "Subtitle"
          placeholder: "A description of your post."
          alterable: true
      - name: "date"
        field:
          element: "text"
          label: "Date"
          help: "Enter date of post."
          placeholder: "yyyy-mm-dd"
          alterable: true
      - name: "published"
        field:
          element: "checkbox"
          label: "Publish"
          help: "Check to publish post, uncheck to hide."

gems:
  - jekyll-paginate

# Beautiful Jekyll / Dean Attali
# 2fc73a3a967e97599c9763d05e564189
